### ISSUE TITLE
Error during update (AttributeError: 'NoneType' object has no attribute 'group')

### ISSUE THREAD

**Issue by Tyree** [pkoenig10/sink#31]
Getting this error in different places on several runs of the update command.

```
Traceback (most recent call last):
  File "sink.py", line 452, in <module>
    main()
  File "sink.py", line 415, in main
    sink.update(args.update_ignored, args.auto_only, args.score_threshold, args.match_limit, args.retries)
  File "sink.py", line 269, in update
    self._update_photos(retries)
  File "sink.py", line 284, in _update_photos
    picture = self.facebook.get_profile_picture(friend_url, self.friends[friend_url])
  File "sink.py", line 166, in get_profile_picture
    user_id = re.search(self.user_id_regex, profile_response.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Any ideas?

Thanks!

**Comment by pkoenig10** [comment]
This indicates that Sink couldn't find the user ID on the friend's profile page.

It looks like you're not using the latest version of Sink. This error is almost certainly because you are being rate limited. This issue was fixed in #30, which improved the behavior when being rate limited and added some options to help avoid rate limiting. Updating Sink to the latest version should resolve this issue.

**Comment by Tyree** [comment]
Okay. So after updating to the latest version, I don't get the error, but after about 40-50 contacts, it starts adding "RATE LIMITED" in front of the names.

So, the question is, how have you gotten around this? What's my next step?

Thanks!

**Comment by pkoenig10** [comment]
There's not really an easy way around this. The `--delay` and `--expiry` options added in #30 may help to reduce the rate limiting. More information about these options can be found in the README and in the usage information by using the `--help` flag.
